name: Asha Ganpat
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87939
title: to the beginning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0502'
    - '#888888'
    - '#aca9a4'
    - '#133b6f'
    - '#502e14'
  brandStrength: 0
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
