name: AshaGanpat
favicon: null
layout_spectrum: 0.5476680579595268
typography_spectrum: 0.24903031601570547
title: "Asha Ganpat's Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0502'
    - '#888888'
    - '#aca9a4'
    - '#133b6f'
    - '#502e14'
  brandStrength: 0
  lightness: 0.7471755971200764
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
